#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  return
else
  echo ""
fi

packages=(
  # Install GNU core utilities (those that come with OS X are outdated)
  coreutils

  # Install Bash 4
  bash

  # Install databases
  sqlite
  mysql
  mongodb

  # Install everything else
  git
  htop
  node
  grc
)

# Make sure we’re using the latest Homebrew
brew update >/dev/null 2>/dev/null

# Upgrade any already-installed formulae
brew upgrade >/dev/null 2>/dev/null

for i in "${packages[@]}"
do
  info "installing $i"
  CMD="brew install $i"
  $CMD >/dev/null 2>/dev/null
  success "$i is now installed"
done

# Remove outdated versions from the cellar
brew cleanup >/dev/null 2>/dev/null

return 0