#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" > /tmp/homebrew-install.log
fi

# The set of packages I want installed by default
packages=(
  # Install GNU core utilities (those that come with OS X are outdated)
  coreutils

  # Install Bash 4
  bash

  # Install everything else
  git
  htop
  node
  grc
  bash-completion
)

# Make sure we’re using the latest Homebrew
info "updating Homebrew"
brew update >/dev/null 2>/dev/null
success "Homebrew is up to date"

# Upgrade any already-installed formulae
info "upgrade installed formulae"
brew upgrade >/dev/null 2>/dev/null
success "Formulae are all up to date"

for i in "${packages[@]}"
do
  info "installing $i"
  CMD="brew install $i"
  $CMD >/dev/null 2>/dev/null
  success "$i is now installed"
done

# Remove outdated versions from the cellar
brew cleanup >/dev/null 2>/dev/null

exit 0
